### ISSUE TITLE
SocketError

### ISSUE THREAD

**Issue by Beyarz** [HatBashBR/HatCloud#1]
Copy from the error:
 ██████╗██╗      ██████╗ ██╗   ██╗██████╗     ██╗  ██╗ █████╗ ████████╗ 
██╔════╝██║     ██╔═══██╗██║   ██║██╔══██╗    ██║  ██║██╔══██╗╚══██╔══╝ 
██║     ██║     ██║   ██║██║   ██║██║  ██║    ███████║███████║   ██║   
██║     ██║     ██║   ██║██║   ██║██║  ██║    ██╔══██║██╔══██║   ██║   
╚██████╗███████╗╚██████╔╝╚██████╔╝██████╔╝    ██║  ██║██║  ██║   ██║   
 ╚═════╝╚══════╝ ╚═════╝  ╚═════╝ ╚═════╝     ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   
Tool for identify IP real of CloudFlare.
Author: Mateus a.k.a Dctor. - HatBash BR
Members HatBashBR: Everton a.k.a  XGU4RD14N, Junior a.k.a ASTAROTH , UrdSys a.k.a Johnny, No one, Geovane, RHood
fb.com/hatbashbr/
github.com/hatbashbr/

Hatcloud.rb:59:in `getaddress': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from Hatcloud.rb:59:in `<main>'
------------------
(program exited with code: 1)

**Comment by mateeuslinno** [comment]
What is site? Send-me.

**Comment by Beyarz** [comment]
I get the error as soon as I run the script.

**Comment by Beyarz** [comment]
Found the problem, you are not supposed to have "https://" or "http://", just "www." or just the domain is allowed.
