### ISSUE TITLE
Can not find real IP?

### ISSUE THREAD

**Issue by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [HatBashBR/HatCloud#10]
[+] Site analysis: kknews.cc
[+] CloudFlare IP is 104.20.200.9
[+] Real IP is
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:363:in `open_http': 404 Not Found (OpenURI::HTTPError)
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:741:in `buffer_open'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:212:in `block in open_loop'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:210:in `catch'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:210:in `open_loop'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:151:in `open_uri'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:721:in `open'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/open-uri.rb:729:in `read'
        from hatcloud.rb:74:in `<main>'

**Comment by hassan-91** [comment]
[+] Site analysis: skystats.com 
[+] CloudFlare IP is 104.24.23.15 
[+] Real IP is 45.79.152.209
/usr/lib/ruby/2.3.0/open-uri.rb:359:in `open_http': 403 Forbidden (OpenURI::HTTPError)
	from /usr/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
	from /usr/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
	from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
	from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
	from /usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
	from /usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
	from /usr/lib/ruby/2.3.0/open-uri.rb:725:in `read'
	from hatcloud.rb:74:in `<main>'

**Comment by soermejo** [comment]
same error

**Comment by Just-Jahid** [comment]
I am also facing the same problem

**Comment by Winterspite** [comment]
The issue is that the script needs better error handling around non-CF domains.

What you're likely hitting is that on line 67 where it says `regex = ....match(response)` -- there likely isn't a regex match.

And what that means is that is that the response from crimeflare.org in the line above (`response = request.body` and `request = Net::HTTP.post_form....`) doesn't contain an IP address of a nameserver.

You can verify by throwing in a `puts response` statement right before line 67 and view the response from Crimeflare. In my case:

```
<HTML><HEAD><META HTTP-EQUIV="content-type"  CONTENT="text/html; charset=UTF-8">
<META NAME="ROBOTS" CONTENT="NOINDEX,NOFOLLOW">
<TITLE>CloudFlare search results</TITLE></HEAD><BODY BGCOLOR=#eeeebe>
<font face="Arial, Helvetica, sans-serif"><BR><blockquote><b>
<font size=5><center>Data for <font color=#c00000>CENSOREDDOMAIN.COM</font></font></center>
<BR>ns2.CENSORED.com
<BR>ns1.CENSORED.com
<BR><BR>Search aborted &#151; these are not CloudFlare-user nameservers.
<BR><BR></b><center><a href="http://www.crimeflare.org/cfs.html#box">Back to search box</a>
</center><BR></blockquote></BODY></HTML>
```
