### ISSUE TITLE
HatCloud Crashing

### ISSUE THREAD

**Issue by savadks95** [HatBashBR/HatCloud#13]
Whhen i tried to find an ip it craches. i tried both windows bash and ubuntu 16.04 the result is same.

ruby hatcloud.rb -b example.gr

██╗  ██╗ █████╗ ████████╗     ██████╗██╗      ██████╗ ██╗   ██╗██████╗ 
██║  ██║██╔══██╗╚══██╔══╝    ██╔════╝██║     ██╔═══██╗██║   ██║██╔══██╗
███████║███████║   ██║       ██║     ██║     ██║   ██║██║   ██║██║  ██║
██╔══██║██╔══██║   ██║       ██║     ██║     ██║   ██║██║   ██║██║  ██║
██║  ██║██║  ██║   ██║       ╚██████╗███████╗╚██████╔╝╚██████╔╝██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝        ╚═════╝╚══════╝ ╚═════╝  ╚═════╝ ╚═════╝ 
Tool for identifying real IP of CloudFlare protected website.
fb.com/hatbashbr/
github.com/hatbashbr/

/usr/lib/ruby/2.3.0/net/http.rb:880:in `initialize': execution expired (Net::OpenTimeout)
	from /usr/lib/ruby/2.3.0/net/http.rb:880:in `open'
	from /usr/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
	from /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /usr/lib/ruby/2.3.0/net/http.rb:584:in `start'
	from /usr/lib/ruby/2.3.0/net/http.rb:508:in `post_form'
	from hatcloud.rb:62:in `<main>'

**Comment by aoc99** [comment]
connection to http://www.crimeflare.org/cgi-bin/cfsearch.cgi is timeout. maybee block by gov or anything

**Comment by aoc99** [comment]
yes.. i was check 2 weeks ago hehe thanks

**Comment by mateeuslinno** [comment]
This problem was resolved.
