### ISSUE TITLE
help

### ISSUE THREAD

**Issue by MeHraTt** [HatBashBR/HatCloud#15]
/usr/lib/ruby/2.3.0/net/http.rb:880:in `initialize': execution expired (Net::OpenTimeout)
	from /usr/lib/ruby/2.3.0/net/http.rb:880:in `open'
	from /usr/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
	from /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /usr/lib/ruby/2.3.0/net/http.rb:584:in `start'
	from /usr/lib/ruby/2.3.0/net/http.rb:508:in `post_form'
	from hatcloud.rb:62:in `<main>'

**Comment by captaincaleb2004** [comment]
Same. I'm guessing the creator of this no longer supports this script

**Comment by mateeuslinno** [comment]
i'm back. I'll resolve this problem.

**Comment by mateeuslinno** [comment]
Problem resolved..
