### ISSUE TITLE
`initialize': execution expired (Net::OpenTimeout)

### ISSUE THREAD

**Issue by captaincaleb2004** [HatBashBR/HatCloud#16]
I'm in kali linux, I opened a terminal, I typed "git clone https://github.com/HatBashBR/HatCloud/ " (Without quotes) then "cd HatClound" (Without quotes) terminal: root@kali:~/HatCloud# . Then when I type:
 "ruby hatcloud.rb --byp 104.27.175.10" (Without quotes)

██╗  ██╗ █████╗ ████████╗     ██████╗██╗      ██████╗ ██╗   ██╗██████╗ 
██║  ██║██╔══██╗╚══██╔══╝    ██╔════╝██║     ██╔═══██╗██║   ██║██╔══██╗
███████║███████║   ██║       ██║     ██║     ██║   ██║██║   ██║██║  ██║
██╔══██║██╔══██║   ██║       ██║     ██║     ██║   ██║██║   ██║██║  ██║
██║  ██║██║  ██║   ██║       ╚██████╗███████╗╚██████╔╝╚██████╔╝██████╔╝
╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝        ╚═════╝╚══════╝ ╚═════╝  ╚═════╝ ╚═════╝ 
Tool for identifying real IP of CloudFlare protected website.
fb.com/hatbashbr/
github.com/hatbashbr/

/usr/lib/ruby/2.3.0/net/http.rb:880:in `initialize': execution expired (Net::OpenTimeout)
	from /usr/lib/ruby/2.3.0/net/http.rb:880:in `open'
	from /usr/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
	from /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /usr/lib/ruby/2.3.0/net/http.rb:584:in `start'
	from /usr/lib/ruby/2.3.0/net/http.rb:508:in `post_form'
	from hatcloud.rb:62:in `<main>'

Please help me I'm not really sure what else to do

**Comment by 1M4Z3N** [comment]
Me to :)

**Comment by mateeuslinno** [comment]
I changed the script.. Problem resolved.
