### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by gearcapitan** [HatBashBR/HatCloud#9]
![kali linux-2017-06-13-09-18-09](https://user-images.githubusercontent.com/13740942/27086941-4a73f298-5019-11e7-8147-e32c9d501128.png)

**Comment by ipatrol** [comment]
It appears crimeflare.com is down. I do not know how long it has been down, or why, but HatCloud is basically just a thin API wrapper around CrimeFlare, so it cannot work without it.
